import type { Metadata } from "next";
import { Grand_Hotel } from "next/font/google";

const grand_hotel = Grand_Hotel({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div
        className={`${grand_hotel.className} w-screen h-screen relative overflow-hidden`}
      >
        <img
          src="/background/bg-img.png"
          alt="Background"
          className="absolute inset-0 w-full h-full object-cover"
        />

        {children}
      </div>
    </html>
  );
}
